### ISSUE TITLE
#FeatureRequest Add support for User defined libraries in c_cpp_properties.json

### ISSUE THREAD

**Issue by noppej** [damogranlabs/VS-Code-STM32-IDE#11]
Firstly, a BIG THANK YOU, for amazing utility. I've used it for my personal project (ex SW4STM project, generated by STM32CubeMX). I'm soooo happy to no longer be locked into Eclipse. Thanks.

#### My request is this: 
Similar to user_cSources, user_cIncludes, etc. It would be great if you could add a user_ldLibs or similar, so that the final build of the .elf file can link in user defined .o files.

**Comment by schperplata** [comment]
Latest revision supports adding linker files. See linker example and additional 'c_cpp_properties.json' fields ('user_ldx' fields).

**Comment by noppej** [comment]
I just had an opportunity to test it, and it works like a dream. BIG Thank you :-)
