### ISSUE TITLE
KeyError: 'settings' 

### ISSUE THREAD

**Issue by EnyuZhuang** [damogranlabs/VS-Code-STM32-IDE#14]
> Traceback (most recent call last):
>   File "ideScripts/update.py", line 88, in <module>
>     wksData = wksFile.addBuildDataToWorkspaceFile(wksData, buildData)
>   File "***\ideScripts\updateWorkspaceFile.py", line 64, in addBuildDataToWorkspaceFile
>     workspaceData["settings"]["cortex-debug.armToolchainPath"] = armToolchainPah
> KeyError: 'settings'

The reason was that in my .code-workspace, there was no "settings" at the beginning. I fixed it by creating a "settings" in my .code-workspace. It would be nice if it can be fixed from python scripts.

BTW: Thanks very much for providing this useful extension.

**Comment by schperplata** [comment]
Fixed in commit adc1f71f4a96d2ffebed3c919663500840cd14e2.
Thank you.
