### ISSUE TITLE
Error during update.py

### ISSUE THREAD

**Issue by JTrotta** [damogranlabs/VS-Code-STM32-IDE#19]
ERROR (77 seconds).
Unexpected error occured during 'Update' procedure. Exception:
[WinError 5] Access denied

Any idea?

**Comment by schperplata** [comment]
Probably a very basic issue - you lack permission to r/w to some file/folder. 
Check workspace folder properties and its permissions.

I will add a traceback data so error location is a little more descriptive. Hovewer, try to google such errors and you will most likely get the answer right away :)

**Comment by JTrotta** [comment]
No problem. It was a path error.

1. Path must be written well (my mistake)
2. Absolutely NO SPACE in paths

It works perfectly
