### ISSUE TITLE
GDB not found

### ISSUE THREAD

**Issue by mmikkone** [damogranlabs/VS-Code-STM32-IDE#29]
When I try to debug, there's message box: "OpenOCD GDB executable "arm-none-eabi-gdb.exe" was not found. Please configure "cortex-debug.armToolchainPath" correctly."

When I run updatePaths.py, it doesn't even ask the path to gdb. Is it missing?

**Comment by schperplata** [comment]
`cortex-debug.armToolchainPath` is updated only on _updateWorkspaceFile.py_. This keys should also be updated, if you run _update.py_.
I will consider adding this also to _updatePaths.py_.

**Comment by schperplata** [comment]
Closing since there was no feedback.
