### ISSUE TITLE
Error when Flashing

### ISSUE THREAD

**Issue by yogypr03** [damogranlabs/VS-Code-STM32-IDE#30]
![1222](https://user-images.githubusercontent.com/53253131/64226992-e9772400-cf0b-11e9-9e44-0235d6ec6540.png)
how to fix it ?

**Comment by schperplata** [comment]
![image](https://user-images.githubusercontent.com/8736111/64492219-1dd34300-d272-11e9-82ce-5083e53cece2.png)
