### ISSUE TITLE
Try build and get this:  "undefined reference to ....

### ISSUE THREAD

**Issue by SergNif** [damogranlabs/VS-Code-STM32-IDE#43]
I am trying compile project. But get mistake.

I tried make simple project for stm32f103c8. It like for me. but this project for Oled 0.96 ssd1306 can`t to compile.

my project https://yadi.sk/d/TUBpLaJGUWKadQ
[Uploading mix.zip…]()
![11](https://user-images.githubusercontent.com/43117411/97919603-1d94e180-1d69-11eb-9969-bca0726088a6.png)

**Comment by SergNif** [comment]
![12](https://user-images.githubusercontent.com/43117411/97920753-f808d780-1d6a-11eb-98c8-db45046a1060.png)

**Comment by schperplata** [comment]
What you are seeing here is not related to ideScripts project, but a basic compile/link -time error. 
What linker (`ld.exe`) is telling you is: `undefined reference to 'SSD1306_Init'` which basically means that you are calling function `SSD1306_Init()` that is not defined or definition can't be discovered by the linker. Make sure you add all source files on correct places and includes are properly resolved.

Closing this issue as it is not related to ideScripts.
